update to gotham rc1, fix Darwin cross problems

diff --git a/package/xbmc/patches/patch-tools_Linux_xbmc_sh_in b/package/xbmc/patches/patch-tools_Linux_xbmc_sh_in
--- a/package/xbmc/patches/patch-tools_Linux_xbmc_sh_in
+++ b/package/xbmc/patches/patch-tools_Linux_xbmc_sh_in
@@ -1,15 +1,61 @@
---- xbmc-12.3-Frodo.orig/tools/Linux/xbmc.sh.in	2013-12-12 22:47:49.000000000 +0100
-+++ xbmc-12.3-Frodo/tools/Linux/xbmc.sh.in	2014-01-14 09:55:27.409527526 +0100
-@@ -52,7 +52,7 @@ single_stacktrace()
+--- xbmc-24032014.orig/tools/Linux/xbmc.sh.in	2014-03-24 15:52:52.000000000 +0100
++++ xbmc-24032014/tools/Linux/xbmc.sh.in	2014-03-27 11:42:33.985822969 +0100
+@@ -23,7 +23,7 @@ prefix="@prefix@"
+ exec_prefix="@exec_prefix@"
+ datarootdir="@datarootdir@"
+ LIBDIR="@libdir@"
+-CRASHLOG_DIR=${CRASHLOG_DIR:-$HOME}
++CRASHLOG_DIR=/tmp/xbmc
  
- print_crash_report()
+ # Check for some options used by this script
+ while [ "$#" -gt "0" ]
+@@ -42,7 +42,7 @@ done
+ single_stacktrace()
  {
--  FILE="$HOME/xbmc_crashlog-`date +%Y%m%d_%H%M%S`.log"
-+  FILE="/tmp/xbmc_crashlog-`date +%Y%m%d_%H%M%S`.log"
-   echo "############## XBMC CRASH LOG ###############" >> $FILE
+   # core filename is either "core.$PID" or "core"
+-  find "$1" -maxdepth $2 -name 'core*' | while read core; do
++  find "$1" -name 'core*' | while read core; do
+       LC_ALL=C gdb --core="$core" --batch 2> /dev/null | grep -q "^Core was generated by \`$LIBDIR/xbmc/xbmc.bin" || continue
+       echo "=====>  Core file: "$core" ($(stat -c%y "$core"))" >> $FILE
+       echo "        =========================================" >> $FILE
+@@ -64,33 +64,14 @@ print_crash_report()
+   uname -m >> $FILE
+   echo -n " Kernel: " >> $FILE
+   uname -rvs >> $FILE
+-  echo -n " Release: " >> $FILE
+-  if [ -f /etc/os-release ]; then
+-	  . /etc/os-release
+-	  echo $NAME $VERSION >> $FILE
+-  elif which lsb_release > /dev/null; then
+-    echo >> $FILE
+-    lsb_release -a 2> /dev/null | sed -e 's/^/    /' >> $FILE
+-  else
+-    echo "lsb_release not available" >> $FILE
+-  fi
+   echo "############## END SYSTEM INFO ##############" >> $FILE
    echo >> $FILE
-   echo "################ SYSTEM INFO ################" >> $FILE
-@@ -91,9 +91,9 @@ print_crash_report()
+   echo "############### STACK TRACE #################" >> $FILE
+   if which gdb >/dev/null 2>&1; then
+-    if which systemd-coredumpctl &> /dev/null; then
+-      systemd-coredumpctl dump -o core xbmc.bin &> /dev/null
+-    fi
+-    single_stacktrace "$PWD" 1
++    single_stacktrace "$PWD"
+     # Find in plugins directories
+-    if [ $XBMC_HOME ]; then
+-      BASEDIR=$XBMC_HOME
+-    else
+-      BASEDIR="$LIBDIR/xbmc/"
+-    fi
+-    single_stacktrace "$BASEDIR" 5
+-    # find in user xbmc dir
+-    single_stacktrace $HOME/.xbmc/ 5
++    BASEDIR="$LIBDIR/xbmc/"
++    single_stacktrace "$BASEDIR"
+   else
+     echo "gdb not installed, can't get stack trace." >> $FILE
+   fi
+@@ -98,9 +79,9 @@ print_crash_report()
    echo >> $FILE
    echo "################# LOG FILE ##################" >> $FILE
    echo >> $FILE
@@ -21,7 +67,7 @@
      echo >> $FILE
    else
      echo "Logfile not found in the usual place." >> $FILE
-@@ -107,12 +107,6 @@ print_crash_report()
+@@ -114,12 +95,6 @@ print_crash_report()
    echo "Crash report available at $FILE"
  }
  
