misc fixes from bulk build

diff --git a/package/sane-backends/patches/patch-configure b/package/sane-backends/patches/patch-configure
--- a/package/sane-backends/patches/patch-configure
+++ b/package/sane-backends/patches/patch-configure
@@ -1,11 +1,90 @@
---- sane-backends-1.0.20.orig/configure	2009-05-03 18:59:22.000000000 +0200
-+++ sane-backends-1.0.20/configure	2010-01-14 19:51:31.000000000 +0100
-@@ -34117,7 +34117,7 @@ ALL_BACKENDS="abaton agfafocus apple art
-         hp5590 hpsj5s hpljm1005 hs2p ibm leo lexmark ma1509 \
+--- sane-backends-1.0.22.orig/configure	2011-02-14 02:27:52.000000000 +0100
++++ sane-backends-1.0.22/configure	2011-10-01 19:32:51.919066675 +0200
+@@ -7529,77 +7529,7 @@ done
+ 
+ 
+ 
+-
+-
+-
+-pkg_failed=no
+-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for LIBV4L" >&5
+-$as_echo_n "checking for LIBV4L... " >&6; }
+-
+-if test -n "$LIBV4L_CFLAGS"; then
+-    pkg_cv_LIBV4L_CFLAGS="$LIBV4L_CFLAGS"
+- elif test -n "$PKG_CONFIG"; then
+-    if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libv4l1\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "libv4l1") 2>&5
+-  ac_status=$?
+-  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+-  test $ac_status = 0; }; then
+-  pkg_cv_LIBV4L_CFLAGS=`$PKG_CONFIG --cflags "libv4l1" 2>/dev/null`
+-else
+-  pkg_failed=yes
+-fi
+- else
+-    pkg_failed=untried
+-fi
+-if test -n "$LIBV4L_LIBS"; then
+-    pkg_cv_LIBV4L_LIBS="$LIBV4L_LIBS"
+- elif test -n "$PKG_CONFIG"; then
+-    if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libv4l1\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "libv4l1") 2>&5
+-  ac_status=$?
+-  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+-  test $ac_status = 0; }; then
+-  pkg_cv_LIBV4L_LIBS=`$PKG_CONFIG --libs "libv4l1" 2>/dev/null`
+-else
+-  pkg_failed=yes
+-fi
+- else
+-    pkg_failed=untried
+-fi
+-
+-
+-
+-if test $pkg_failed = yes; then
+-   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+-$as_echo "no" >&6; }
+-
+-if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+-        _pkg_short_errors_supported=yes
+-else
+-        _pkg_short_errors_supported=no
+-fi
+-        if test $_pkg_short_errors_supported = yes; then
+-	        LIBV4L_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libv4l1" 2>&1`
+-        else
+-	        LIBV4L_PKG_ERRORS=`$PKG_CONFIG --print-errors "libv4l1" 2>&1`
+-        fi
+-	# Put the nasty error message in config.log where it belongs
+-	echo "$LIBV4L_PKG_ERRORS" >&5
+-
+-	have_libv4l1=no
+-elif test $pkg_failed = untried; then
+-     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+-$as_echo "no" >&6; }
+-	have_libv4l1=no
+-else
+-	LIBV4L_CFLAGS=$pkg_cv_LIBV4L_CFLAGS
+-	LIBV4L_LIBS=$pkg_cv_LIBV4L_LIBS
+-        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+-$as_echo "yes" >&6; }
+-	have_libv4l1=yes
+-fi
++have_libv4l1=no
+ 
+ 
+ 
+@@ -16874,7 +16804,7 @@ ALL_BACKENDS="abaton agfafocus apple art
+         leo lexmark ma1509 magicolor \
          matsushita microtek microtek2 mustek mustek_pp \
          mustek_usb mustek_usb2 nec net niash pie pint \
 -        pixma plustek plustek_pp qcam ricoh rts8891 s9036 \
 +        pixma plustek plustek_pp ricoh rts8891 s9036 \
          sceptre sharp sm3600 sm3840 snapscan sp15c st400 \
          stv680 tamarack teco1 teco2 teco3 test u12 umax
-         umax_pp umax1220u v4l xerox_mfp"
+         umax_pp umax1220u v4l xerox_mfp p5"
