better error handling

diff --git a/package/adkinstall/src/adkinstall b/package/adkinstall/src/adkinstall
--- a/package/adkinstall/src/adkinstall
+++ b/package/adkinstall/src/adkinstall
@@ -180,6 +180,10 @@ if [ $f -eq 1 ];then exit 1;fi
 function create_label {
 	print "creating empty partition table"
 	parted -s $1 mklabel msdos > /dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		echo "creating empty partition failed!"
+		exit 1
+	fi
 }
 
 # get max size of disk in sectors
@@ -193,31 +197,55 @@ function get_max_size {
 function create_partition {
 	print creating partition on $1
 	parted -s $1 unit s mkpart primary $2 $3 $4 > /dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		echo "creating primary partition failed!"
+		exit 1
+	fi
 }
 
 function set_boot_flag {
 	print setting bootflag on $1 partition $2
 	parted -s $1 set $2 boot on > /dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		echo "setting bootflag failed!"
+		exit 1
+	fi
 }
 
 function change_part_type {
 	print setting partition type on $1 partition $2 to $3
 	sfdisk --change-id $1 $2 $3 >/dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		echo "changing partition type failed!"
+		exit 1
+	fi
 }
 
 function create_filesystem {
 	print creating filesystem $2 on $1 partition $3
 	mkfs.$2 -F -q ${1}${3}
+	if [ $? -ne 0 ]; then
+		echo "creating filesystem on partition failed!"
+		exit 1
+	fi
 }
 
 function mount_fs {
 	print mounting ${1}${2} to $4 with filesystem $3
 	mount -t $3 ${1}${2} $4
+	if [ $? -ne 0 ]; then
+		echo "mounting filesystem failed!"
+		exit 1
+	fi
 }
 
 function extract_archive {
 	print extracting archive $1 onto $2
 	tar -C $2 -xpf $1
+	if [ $? -ne 0 ]; then
+		echo "archive extraction failed!"
+		exit 1
+	fi
 }
 
 function grub_install {
@@ -225,16 +253,20 @@ function grub_install {
 (
         print set default=0
         print set timeout=1
-        print serial --unit=0 --speed=$speed
+        print serial --unit=0 --speed=115200
         print terminal_output serial
         print terminal_input serial
-        consargs="console=ttyS0,$speed"
+        consargs="console=ttyS0,115200"
         print
         print 'menuentry "GNU/Linux (OpenADK)" {'
         print "\tlinux /boot/kernel root=/dev/sda1"
         print '}'
 ) >/mnt/boot/grub/grub.cfg
 	grub-install $1 --root-directory /mnt
+	if [ $? -ne 0 ]; then
+		echo "grub install failed!"
+		exit 1
+	fi
 }
 
 function fix_perm {
