verbose (by default, deactivatable) init scripts

diff --git a/package/base-files/src/etc/init.d/rcK b/package/base-files/src/etc/init.d/rcK
--- a/package/base-files/src/etc/init.d/rcK
+++ b/package/base-files/src/etc/init.d/rcK
@@ -1,9 +1,20 @@
 #!/bin/sh
 export PATH=/bin:/sbin:/usr/bin:/usr/sbin
+: ${rcquiet=0}
 {
 	grep '^#INIT ' /etc/init.d/* | \
 	    sort -rnk2 | \
 	    while read line; do
+		test x"$rcquiet" = x"0" && echo -n "Stopping ${line%%:*}... "
 		sh ${line%%:*} autostop
+		rc=$?
+		case $rcquiet:$rc in
+		(0:0)
+			echo done.
+			;;
+		(0:*)
+			echo "failed ($rc)."
+			;;
+		esac
 	done
 } | logger -s -p 6 -t ''
diff --git a/package/base-files/src/etc/init.d/rcS b/package/base-files/src/etc/init.d/rcS
--- a/package/base-files/src/etc/init.d/rcS
+++ b/package/base-files/src/etc/init.d/rcS
@@ -6,10 +6,21 @@ fi
 ln -s /proc/self/fd/2 /dev/stderr
 echo "System initialization ..."
 export PATH=/bin:/sbin:/usr/bin:/usr/sbin
+: ${rcquiet=0}
 {
 	grep '^#INIT ' /etc/init.d/* | \
 	    sort -nk2 | \
 	    while read line; do
+		test x"$rcquiet" = x"0" && echo -n "Starting ${line%%:*}... "
 		sh ${line%%:*} autostart
+		rc=$?
+		case $rcquiet:$rc in
+		(0:0)
+			echo done.
+			;;
+		(0:*)
+			echo "failed ($rc)."
+			;;
+		esac
 	    done
 } |tee /dev/stderr |logger -p 6 -t ''
