scripts/ipkg-build: fix error message
Signed-off-by: Phil Sutter <phil@nwl.cc>

diff --git a/scripts/ipkg-build b/scripts/ipkg-build
--- a/scripts/ipkg-build
+++ b/scripts/ipkg-build
@@ -106,7 +106,7 @@ You probably want to remove them: " >&2
 	[ "$?" -ne 0 ] && PKG_ERROR=1
 
 	if echo $pkg | grep '[^a-z0-9.+-]'; then
-		echo "*** Error: Package name $name contains illegal characters, (other than [a-z0-9.+-])" >&2
+		echo "*** Error: Package name $pkg contains illegal characters, (other than [a-z0-9.+-])" >&2
 		PKG_ERROR=1;
 	fi
 
